create database payhere1;
use payhere1;

-- GWASE1테이블 기준으로 2002년에 응암동으로 되어져있는 1111111111111 납세자를 추출해주세요.
SELECT GWASE1.*
FROM GWASE1
JOIN GWASE_HDONG ON GWASE1.C_HDONG = GWASE_HDONG.C_HDONG
WHERE GWASE_HDONG.CN_HDONG = '응암동' AND GWASE1.TPR_NO;

-- 각 납세자(TPR_NO) 기준으로 년도별(Y_GWASE)+행정동(C_HDONG)별의 부과납(BUGWA_NAP), 체납(CHE_NAP) 의 합계를 구해주세요.
SELECT GWASE2.Y_GWASE AS '년도'
       , GWASECN.CN_HDONG AS '행정동'
       , GWASECN.TPR_NO AS '납세자'
      , SUM(GWASE2.BUGWA_NAP) AS '납세총액'
      , SUM(GWASE2.CHE_NAP) AS '체납총액'
FROM GWASE2
JOIN (SELECT GWASE1.*
			 , GWASE_HDONG.CN_HDONG AS CN_HDONG
	  FROM GWASE1
	  JOIN GWASE_HDONG 
      ON GWASE1.C_HDONG = GWASE_HDONG.C_HDONG) GWASECN
ON GWASE2.Y_GWASE = GWASECN.Y_GWASE 
	AND GWASE2.M_GWASE = GWASECN.M_GWASE 
	AND GWASE2.S_GWASE = GWASECN.S_GWASE 
	AND GWASE2.C_HDONG = GWASECN.C_HDONG
GROUP BY GWASE2.Y_GWASE, GWASECN.CN_HDONG ,GWASECN.TPR_NO
ORDER BY GWASE2.Y_GWASE, GWASECN.CN_HDONG ,GWASECN.TPR_NO;
